[
project
]  # Changed from "[<newline>project<newline>]"
name = "checkmate-sample"
version = "0.1.0"
description = "A sample project with checkerboard functionality"
authors = [
    {name = "Thomas Martin", email = "tmartin@ucar.edu"},
]
dependencies = [
    "numpy>=1.26.0",
    "xarray>=2023.8.0",
]
requires-python = ">=3.9"
readme = "README.md"

[
project.optional-dependencies
]  # Changed from "[<newline>project.optional-dependencies<newline>]"
dev = [
    "pytest>=7.4.0",
]

[
build-system
]  # Changed from "[<newline>build-system<newline>]"
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"