name: Build, Test, and Publish Python Package
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Minimum version specified in your pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest twine
        pip install .
    - name: Run tests
      run: pytest
    - name: Build package
      if: success()
      run: |
        python -m build
        echo "Package built successfully"
        ls -l dist/
    - name: Upload dist
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Twine
      run: pip install twine
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/
    - name: List contents of dist directory
      run: ls -l dist/
    - name: Publish distribution to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "Attempting to upload to PyPI..."
        twine check dist/*
        twine upload --verbose dist/*
