name: Build and Create Distribution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Minimum version specified in your pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest
        pip install .
    - name: Run tests
      run: pytest
    - name: Build package
      if: success()
      run: python -m build
    - name: Upload dist
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
